/* eslint-disable */
/**
 * This file was automatically generated by enrolla.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source customer configuration file,
 * and run enrolla to regenerate this file.
 */

import { ConfigClient } from '@enrolla/enrolla-ts';

export class Tenant {
  constructor(private objectId: string) {}

  /**
   * Auth0 Organization ID
   */
  async orgId(): Promise<string> {
    return (await ConfigClient.get(this.objectId, 'orgId')) as Promise<string>;
  }

  async schemaPath(): Promise<string | undefined> {
    return (await ConfigClient.get(
      this.objectId,
      'schemaPath'
    )) as Promise<string>;
  }
}
