export const ORGANIZATION_MANAGER_TYPE = {
  NONE: 'NONE',
  AUTH0: 'AUTH0',
  PROPEL_AUTH: 'PROPEL_AUTH',
} as const;

export type OrganizationManagerType =
  typeof ORGANIZATION_MANAGER_TYPE[keyof typeof ORGANIZATION_MANAGER_TYPE];

export const ORGANIZATION_MANAGER_TYPE_CONFIGURATION_KEY =
  'ORGANIZATION_MANAGER_TYPE';

export const ORGANIZATION_MANAGER_CONFIGURATION_KEY =
  'ORGANIZATION_MANAGER_CONFIGURATION';

export const ORGANIZATION_MANAGER_SECRET_CONFIGURATION_KEY =
  'ORGANIZATION_MANAGER_SECRET_CONFIGURATION';
