name: 'NPM install (with cache)'
runs:
  using: 'composite'
  steps:
    # see: https://github.com/actions/cache/blob/main/examples.md#node---npm
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache NPM cache dir + node_modules
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.npm-cache-dir.outputs.dir }}
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install (on cache miss)
      if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
