name: Deploy all assets

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.change_log_create.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog
        id: change_log_create
        uses: TriPSs/conventional-changelog-action@v3
        with:
          tag-prefix: ''
          git-user-name: ${{ github.event.pusher.name }}
          github-token: ${{ secrets.github_token }}
          git-user-email: ${{ github.event.pusher.email }}

  publish-docker:
    name: Publish docker image to ECR
    needs: release
    if: ${{ needs.release.outputs.tag != '' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_DEFAULT_ROLE }}
          role-session-name: GithubActions
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: 'Install Dependencies'
        run: npm install

      - name: Docker Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/customeric-server
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=sha-
            type=raw,value=${{ needs.release.outputs.tag }}

      - name: 'Build images'
        run: npx nx run-many --target=container --parallel=2
        env:
          INPUT_TAGS: ${{ steps.meta.outputs.tags }}
          INPUT_PUSH: true

  deploy-docker:
    name: Deploy to staging
    needs: [release, publish-docker]
    if: ${{ needs.release.outputs.tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1

      - name: Create and deploy release
        uses: OctopusDeploy/create-release-action@v1
        with:
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          server: ${{ secrets.OCTOPUS_SERVER }}
          space: ${{ secrets.OCTOPUS_SPACE }}
          project: 'customeric-server'
          deploy_to: 'Staging'
          release_number: ${{ needs.release.outputs.tag }}
