name: CI
on:
  pull_request:

env:
  # Workaround since nrwl/nx-set-shas@v3 is currently buggy
  NX_BASE: ${{ github.event.pull_request.base.sha }}
  NX_HEAD: ${{ github.event.pull_request.head.sha }}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: npm ci
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
