name: Publish Packages to NPM

on:
  push:
    branches:
      - 'publishable_package'

jobs:
  affected-packages:
    name: List affected publishable packages
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.set-affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install (on cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Set Affected
        id: set-affected
        run: |
          echo ::set-output name=affected::"$(npx nx print-affected --target=publish --type=lib | jq -c .projects)"

  npm-publish:
    runs-on: ubuntu-latest
    needs: affected-packages
    strategy:
      matrix:
        project: ${{ fromJson(needs.affected-packages.outputs.affected) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install (on cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Test
        id: test
        run: npx nx run-many --target=test --projects=${{ matrix.project }}

      - name: Publish
        id: publish
        run: npx nx run-many --target=publish --projects=${{ matrix.project }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
